services:

  db:
    image: postgres:15

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DevOpsLab123!
      POSTGRES_DB: commandcenter

    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend

    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:DevOpsLab123!@db:5432/commandcenter

    depends_on:
      - db


  frontend:
    build: ./frontend

    ports:
      - "5173:5173"

    depends_on:
        - backend


volumes:
  postgres_data: