apiVersion: v1
kind: ServiceAccount

metadata:
  name: external-secrets-sa
  namespace: devops-command-center
  annotations:
    azure.workload.identity/client-id: "2f14122b-dd5c-4ce1-9167-6ba0802c8f54"