apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: postgres-secret
  namespace: devops-command-center

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore

  target:
    name: postgres-secret

  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-password

    - secretKey: DATABASE_URL
      remoteRef:
        key: database-url