apiVersion: external-secrets.io/v1
kind: SecretStore

metadata:
  name: azure-keyvault
  namespace: devops-command-center

spec:
  provider:
    azurekv:
      vaultUrl: "https://kv-devops-command-center.vault.azure.net/"

      tenantId: "28f9d355-136c-48d5-a6ca-397aa9104618"

      authType: WorkloadIdentity

      serviceAccountRef:
        name: external-secrets-sa