name: CI-CD

on:
  push:
    branches:
      - main

    

  pull_request:




jobs:
  build-and-push:

    runs-on: ubuntu-latest


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Backend Image
        run: |
          docker build \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/backend:${IMAGE_TAG} \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest \
          ./backend

      - name: Build Frontend Image
        run: |
          docker build \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:${IMAGE_TAG} \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest \
          ./frontend

      