apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: devops-command-center

type: Opaque

stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: DevOpsLab123!
  POSTGRES_DB: commandcenter
  DATABASE_URL: postgresql://postgres:DevOpsLab123!@db:5432/commandcenter